name: Deploy version to production

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Trigger lambda for build of index.html from AWS CLI
      run: >-
        aws lambda invoke
        --function-name deploy_prod
        --payload '{ "sha": "${{github.sha}}" }'
        response.json
